language: python
matrix:
  include:
  - python: 3.6
    env: TOX_ENV=py36,flake8,scripts
  - python: 2.7
    env: TOX_ENV=py27,flake8,scripts
install:
  - pip install tox
script:
  - tox -r -e $TOX_ENV
