site_name: PerfKitBenchmarker
site_description: PerfKitBenchmarker home page.
site_url: https://googlecloudplatform.github.io/PerfKitBenchmarker/
repo_url: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker
repo_name: GoogleCloudPlatform/PerfKitBenchmarker

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
  logo: img/pkb-logo.svg

nav:
  - Home: index.md
  - Tutorials: tutorials.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker
      name: PerfKitBenchmarker on GitHub

