
[global]
ioengine=libaio
invalidate=1
direct=1
runtime=10
time_based
filename=/dev/disk/by-id/google-pkb-7fb0c9d8-0-data-0-0
do_verify=0
verify_fatal=0
randrepeat=0
group_reporting=1
percentile_list=1:5:10:20:25:30:40:50:60:70:75:80:90:95:99:99.5:99.9:99.95:99.99

[rand_16k_read_100%-io-depth-1-num-jobs-2]
stonewall
rw=randread
blocksize=16k
iodepth=1
size=100%
numjobs=2

[rand_16k_write_100%-io-depth-1-num-jobs-2]
stonewall
rw=randwrite
blocksize=16k
iodepth=1
size=100%
numjobs=2
