#./pkb.py --benchmarks=netperf --benchmark_config_file=docker_to_cloud.yaml --ip_addresses=EXTERNAL

netperf:
  vm_groups:
    vm_1:
      cloud: Docker
    vm_2:
      vm_spec:
        GCP:
          machine_type: n1-standard-1
          zone: us-central1-a
