# VPN iperf config.
iperf_vpn:
  description: Run iperf over vpn 
  flags:
    iperf_vpn_sending_thread_count: 20
    use_vpn: True
    # vpn_tunnels: 1 # create multiple tunnels for ecmp load balance testing
    #zones: us-central1-a, us-west1-c
  vpn_service:
    tunnel_count: 1
  vm_groups:
    vm_1:
      cloud: GCP
      cidr: 10.0.1.0/24
      zone: us-central1-a
      #vm_spec: 
            #zone: us-central1-a            
            #gce_subnet_region: us-central1  <--global
            #gce_subnet_addr: 10.0.1.0/24    <--global 
    vm_2:
      cloud: GCP
      cidr: 192.168.1.0/24
      zone: us-west1-c
      #vm_spec:
            #zone: us-west1-c            
            #gce_subnet_region: us-west1     <--global
            #gce_subnet_addr: 192.168.1.0/24 <--global
