# VPN iperf config.
iperf:
  description: Run iperf over vpn
  flags:
    iperf_sending_thread_count: 5
    use_vpn: True
    vpn_service_gateway_count: 1
  vpn_service:
    tunnel_count: 1  # create multiple tunnels for ecmp load balance testing
    shared_key: FEEDDAD
    ike_version: 1
    routing_type: static
  vm_groups:
    vm_1:
      cloud: GCP
      cidr: 10.0.1.0/24
      vm_spec:
        GCP:
            machine_type: n1-standard-4
            zone: us-west1-b
    vm_2:
      cloud: AWS
      cidr: 192.168.1.0/24
      vm_spec:
        AWS:
            #machine_type: m5.large
            machine_type: t2.micro
            zone: us-east-2b