; Copyright 2014 PerfKitBenchmarker Authors. All rights reserved.
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
;   http://www.apache.org/licenses/LICENSE-2.0
;
; Unless required by applicable law or agreed to in writing, software
; distributed under the License is distributed on an "AS IS" BASIS,
; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
; See the License for the specific language governing permissions and
; limitations under the License.

[global]
filesize=10*10*1000*$mb_memory
filename=fio_test_file
directory=/scratch0
ioengine=libaio

[sequential_write]
overwrite=0
rw=write
blocksize=512k
size=10*10*1000*$mb_memory
iodepth=64
direct=1
end_fsync=1

[sequential_read]
stonewall
invalidate=1
overwrite=0
rw=read
blocksize=512k
size=10*10*1000*$mb_memory
iodepth=64
direct=1

[random_write_test]
stonewall
overwrite=1
rw=randwrite
blocksize=4k
iodepth=1
size=10*1000*$mb_memory
direct=1

[random_read_test]
invalidate=1
stonewall
rw=randread
blocksize=4k
iodepth=1
size=10*1000*$mb_memory
direct=1

[random_read_test_parallel]
invalidate=1
stonewall
rw=randread
blocksize=4k
iodepth=64
size=10*1000*$mb_memory
direct=1
