intrate,fprate:
submit = echo "${command}" > run.sh ; $BIND bash run.sh
bind0  = /usr/bin/numactl --physcpubind=0 -m 0
bind1  = /usr/bin/numactl --physcpubind=1 -m 0
bind2  = /usr/bin/numactl --physcpubind=2 -m 0
bind3  = /usr/bin/numactl --physcpubind=3 -m 0
bind4  = /usr/bin/numactl --physcpubind=4 -m 0
bind5  = /usr/bin/numactl --physcpubind=5 -m 0
bind6  = /usr/bin/numactl --physcpubind=6 -m 0
bind7  = /usr/bin/numactl --physcpubind=7 -m 0
bind8  = /usr/bin/numactl --physcpubind=8 -m 0
bind9  = /usr/bin/numactl --physcpubind=9 -m 0
bind10  = /usr/bin/numactl --physcpubind=10 -m 0
bind11  = /usr/bin/numactl --physcpubind=11 -m 0
bind12  = /usr/bin/numactl --physcpubind=12 -m 0
bind13  = /usr/bin/numactl --physcpubind=13 -m 0
bind14  = /usr/bin/numactl --physcpubind=14 -m 0
bind15  = /usr/bin/numactl --physcpubind=15 -m 0
